# Generated by Django 5.1.6 on 2025-02-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_books_per_borrow', models.PositiveIntegerField(default=3)),
            ],
        ),
        migrations.AddField(
            model_name='borrow',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
