# Generated by Django 5.1.6 on 2025-02-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_borrowsetting_borrow_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowSetting',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='quantity',
        ),
        migrations.AddField(
            model_name='borrow',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
