# Generated by Django 5.1.6 on 2025-02-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0005_alter_borrowrequest_requested_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
