# Generated by Django 5.1.6 on 2025-02-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0006_borrowrequest_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
